### ISSUE TITLE
amplify-meta.json is corrupt but still parsed properly, #current-cloud-backend is permanently broken

### ISSUE THREAD

**Issue by kevinlam92** [aws-amplify/amplify-cli#10767]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v17.8.0

### Amplify CLI Version

9.1.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes were made before this happened.

### Amplify Categories

Not applicable

### Amplify Commands

push

### Describe the bug

For a while now my amplify-meta.json becomes routinely corrupt every time I use amplify push. Every time I amplify push I most likely have to copy the amplify-meta.json from #current-cloud-backend

I made 2 changes to my lambda function back to back, first deployment with amplify push worked fine... however after closer inspection it appears my amplify-meta.json was indeed corrupt.

Usually the json parser would catch that it was corrupt but this time the corruption caused the JSON file to corrupt at the point where it was still parsable. This caused the #current-cloud-backend to now have a corrupt amplify-meta.json file. 

I cannot seem to be able to recover my last known good configuration and even if I would try to make progress the corruption of the file continues happening. I do not have bucket versioning enabled in my deployment bucket so I cant find older versions of #current-cloud-backend.

See attached for the amplify-meta.json in question.

[redacted]

The corruption wiped out about 6 resources. I was able to figure out what they were supposed to be however without the "lastPushDirHash", I'm unable to recreate a copy of my old non-corrupted workspace.

How is lastPushDirHash generated? Is there a way I can manually piece together my old amplify-meta.json. 
Also what causes this file corruption nonstop?

### Expected behavior

A deterministic workspace with a proper revertable #current-cloud-backend.

### Reproduction steps

1.) amplify push
2.) metadata corrupts (random)
3.) be (unlucky) enough such that the json is still parsable and considered working

### GraphQL schema(s)

n/a

### Project Identifier

2b025cb2062e63e102ce731b9e1451ef

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by kevinlam92** [comment]
Basically this is what happens when it corrupts:

1.) I make some changes locally.
2.) I do `amplify push`

At this point its a coin toss, sometimes I can push properly. Sometimes, amplify-meta.json gets messed up. It's almost like the write buffer got messed up or something. In my uploaded sample of my corrupted amplify-meta.json file I see a whole lot of \u0000 suddenly appearing in the file. Then other chunks of the file are fine.

Now USUALLY, if a bunch of messed up things get written there, the parser would throw an error because it's an invalid JSON file. In this case, that bunch of \u0000 got inserted right between some quotes and overwrote like 6 resources worth of metadata. This got parsed CORRECTLY and amplify was able to deploy using this messedup metadata. #current-cloud-backend got overwritten with this and now I'm stuck.

The only workaround I have right now is migrating into an entirely new environment for backend and migrate existing data over.

You guys should really enable bucket versioning for #current-cloud-backend in the s3 bucket, or make it an option. Because as I understand it once that deployment package is up there I cannot revert to any other working state.

**Comment by kevinlam92** [comment]
As for lastUpdatedHash, I only ask that because I'm desperately trying to piece together what my previous amplify-meta.json would have looked like (I can put the stream ARNs, names whatever in manually). The only thing I don't know is how your lastUpdatedHash is calculated

**Comment by kevinlam92** [comment]
I updated my Mac from Big Sur to Monterey and the corruption has seemed to stop. But please please enable versioning or find some ways of archiving older deployment packages because it's super risky.

I've had to create a brand new amplify backend environment and need to find a way to migrate my data to the new stack without affecting customers.

**Comment by josefaidt** [comment]
Hey @kevinlam92 :wave: apologies for the delay here! Glad to hear you're back up and running despite the oddities and although I have not been able to successfully reproduce this behavior. 

> But please please enable versioning or find some ways of archiving older deployment packages because it's super risky.

Would you be open to filing a separate [feature request](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=2.feature_request.yaml) for this to succinctly capture the request and details?

**Comment by biller-aivy** [comment]
Do you have more than One Frontend connected to the backend via amplify console?

**Comment by kevinlam92** [comment]
> Do you have more than One Frontend connected to the backend via amplify console?

I do actually

> Hey @kevinlam92 👋 apologies for the delay here! Glad to hear you're back up and running despite the oddities and although I have not been able to successfully reproduce this behavior.
> 
> > But please please enable versioning or find some ways of archiving older deployment packages because it's super risky.
> 
> Would you be open to filing a separate [feature request](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=2.feature_request.yaml) for this to succinctly capture the request and details?

I will do that

**Comment by biller-aivy** [comment]
> 
> 
> > Do you have more than One Frontend connected to the backend via amplify console?
> 
> 
> 
> I do actually, one React Native front end and one React front end
> 
> 
> 
> > Hey @kevinlam92 👋 apologies for the delay here! Glad to hear you're back up and running despite the oddities and although I have not been able to successfully reproduce this behavior.
> 
> > 
> 
> > > But please please enable versioning or find some ways of archiving older deployment packages because it's super risky.
> 
> > 
> 
> > Would you be open to filing a separate [feature request](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=2.feature_request.yaml) for this to succinctly capture the request and details?
> 
> 
> 
> I will do that

I am sure, that Not the amplify Push of the cli is the Problem. I have the Same error like you. 

So you could Play with "redeploy this Version" in amplify console, than i guess the file will be corrupted again. 

Would ne nice if you can Test it. Just Go to the deployment bucket before and backup the current-cloud-backup zip.

**Comment by biller-aivy** [comment]
@kevinlam92 any Info here?

**Comment by kevinlam92** [comment]
I gave up trying to fix my old env, moving on to new env now I don't see any more issues with my meta file. You can probably close this, I'll submit a feature req about enabling bucket versioning for #current-cloud-backend

**Comment by josefaidt** [comment]
Hey @kevinlam92 and @biller-aivy we're going to use this issue to track the inconsistencies with backends from other apps, however in the mean time given the update I will close this for now.
