### ISSUE TITLE
Headless amplify init + amplify push -> Auth Parameters must have values Error

### ISSUE THREAD

**Issue by conorw** [aws-amplify/amplify-cli#11208]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

10.3.0

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

auth

### Amplify Commands

init, push

### Describe the bug

When using the latest version of the cli, a headless amplify init, followed by amplify push will give the following error for Auth resources:

Rolling back to v10.0.0 works.

UPDATE_FAILED   Parameters: [autoVerifiedAttributes, allowUnauthenticatedIdentities, hostedUI, smsVerificationMessage, breakCircularDependency, mfaTypes, userpoolClientGenerateSecret, mfaConfiguration, thirdPartyAuth, permissions, adminQueries, resourceNameTruncated, userPoolGroups, smsAuthenticationMessage, passwordPolicyMinLength, userPoolName, userpoolClientWriteAttributes, dependsOn, useEnabledMfas, parentStack, resourceName, triggers, unauthRoleArn, requiredAttributes, authTriggerConnections, aliasAttributes, userpoolClientLambdaRole, usernameAttributes, authRoleArn, authProviders, userpoolClientReadAttributes, emailVerificationSubject, sharedId, useDefault, identityPoolName, userPoolGroupList, authSelections, usernameCaseSensitive, serviceName, emailVerificationMessage, userpoolClientRefreshTokenValidity, userpoolClientSetAttributes, passwordPolicyCharacters, defaultPasswordPolicy] must have values

Here is the init.sh 

```sh
#!/bin/bash
set -e
IFS='|'

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"${AWS_ACCESS_KEY_ID}\",\
\"secretAccessKey\":\"${AWS_SECRET_ACCESS_KEY}\",\
\"region\":\"us-east-1\"\
}"
AMPLIFY="{\
\"projectName\":\"triaxle-server\",\
\"envName\":\"${ENV}\",\
\"appId\":\"${APP_ID}\",\
\"defaultEditor\":\"code\"\
}"
FRONTEND="{\
\"frontend\":\"ios\"
}"
PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"
CODEGEN="{\
\"generateCode\":true,\
\"codeLanguage\":\"typescript\",\
\"fileNamePattern\":\"graphql/**/*.graphql\",\
\"generatedFileName\":\"API.ts\",\
\"generateDocs\":true,\
\"maxDepth\":2\
}"
AUTHCONFIG="{\
    \"appleAppId\":\"${AMPLIFY_APPLE_ID}\",\
    \"googleAppIdUserPool\":\"${AMPLIFY_GOOGLE_CLIENT_ID}\",\
    \"googleClientId\":\"${AMPLIFY_GOOGLE_CLIENT_ID}\",\
    \"googleAppSecretUserPool\":\"${AMPLIFY_GOOGLE_CLIENT_SECRET}\"
    }"

CATEGORIES="{\
\"auth\":$AUTHCONFIG\
}"
amplify init \
--amplify $AMPLIFY \
--categories $CATEGORIES \
--frontend $FRONTEND \
--providers $PROVIDERS \
--codegen $CODEGEN \
--yes
```

here is the push.sh

```sh
#!/bin/bash
set -e
IFS='|'
# TODO: Remove destructive updates
amplify push --yes --force --allow-destructive-graphql-schema-updates
```

### Expected behavior

Successful deployment

### Reproduction steps

1. Add auth to the project
2. Manually deploy
3. Create CI pipeline
4. Use the .sh commands above to headless deploy

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Project Identifier

306e76a8434b9600914289d39e7942af

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Works with v10.0.0

**Comment by josefaidt** [comment]
Hey @conorw :wave: thanks for raising this! After reproducing [another issue](https://github.com/aws-amplify/amplify-cli/issues/11211#issuecomment-1284121725) it appears similar to this one, although I was not able to get this specific error on push. Are you experiencing an issue with init as described in the linked issue?

**Comment by conorw** [comment]
thanks @josefaidt I think you are correct, the issues are related/duplicates.
Will I close this one?

**Comment by ykethan** [comment]
Hey @conorw, please feel free in adding any information on your use case and behaviour you are experiencing in the issue https://github.com/aws-amplify/amplify-cli/issues/11211. I will be closing this issue to prevent any miscommunication between issues.

**Comment by josefaidt** [comment]
Hey @conorw sorry for the delay but let me take a second pass at this one. It almost appears the headless inputs are not being merged with your existing config
