### ISSUE TITLE
An error occurred during the push operation: EPERM: operation not permitted, copyfile /amplify/.temp/#current-cloud-backend/amplify-meta.json

### ISSUE THREAD

**Issue by sean2gh** [aws-amplify/amplify-cli#8413]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.10.0

### Amplify CLI Version

6.2.1

### What operating system are you using?

Ubuntu

### Amplify Categories

auth, storage, function, api, hosting

### Amplify Commands

publish, pull, push

### Describe the bug

I cannot publish, pull or push my amplify project. I did a fresh reinstall of windows and WSL Ubuntu and reinstalled amplify, logged in with amplify configure and now I am getting this error every time I try to publish or push:

```
✖ There was an error pulling the backend environment dev.
An error occurred during the push operation: EPERM: operation not permitted, copyfile '/mnt/d/Projects/fi/amplify/.temp/#current-cloud-backend/amplify-meta.json' -> '/mnt/d/Projects/fi/amplify/#current-cloud-backend/amplify-meta.json'
```

When I try to pull:

`Backend environment 'dev' found. Initializing...
Failed to pull the backend.
EPERM: operation not permitted, copyfile '/mnt/d/Projects/fi/amplify/.temp/#current-cloud-backend/amplify-meta.json' -> '/mnt/d/Projects/fi/amplify/#current-cloud-backend/amplify-meta.json'
Error: EPERM: operation not permitted, copyfile '/mnt/d/Projects/fi/amplify/.temp/#current-cloud-backend/amplify-meta.json' -> '/mnt/d/Projects/fi/amplify/#current-cloud-backend/amplify-meta.json'
    at Object.copyFileSync (node:fs:2800:3)
    at copyFile (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:68:8)
    at onFile (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:53:25)
    at getStats (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:48:44)
    at startCopy (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at copyDirItem (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:120:10)
    at /home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:39
    at Array.forEach (<anonymous>)
    at copyDir (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:113:23)
    at onDir (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:103:10)
    at getStats (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:45:37)
    at startCopy (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:38:10)
    at handleFilterAndCopy (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:33:10)
    at Object.copySync (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:26:10)
    at downloadBackend (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/attach-backend.js:369:8)
    at Object.run (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/attach-backend.js:78:3)
    at Object.attachBackend (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/index.ts:48:3)
    at Object.queryProvider (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/attach-backend-steps/a10-queryProvider.ts:12:3)
    at Object.attachBackend (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/attach-backend.ts:20:5)
    at Object.run (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/commands/pull.ts:59:5)
    at Object.executeAmplifyCommand (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/index.ts:373:5)
    at executePluginModuleCommand (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:177:3)
    at Object.executeCommand (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/execution-manager.ts:29:5)
    at Object.run (/home/sean2evo/.nvm/versions/node/v16.10.0/lib/node_modules/@aws-amplify/cli/src/index.ts:205:5)`

### Expected behavior

I expect it to redeploy my cloud resources on amplify.

### Reproduction steps

1. amplify configure
2. amplify push

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by sean2gh** [comment]
I fixed it by copying a .temp folder #current-cloud-backup into my amplify directory and its working now.
