### ISSUE TITLE
amplify-meta.json regularly corrupting and push failing

### ISSUE THREAD

**Issue by samputer** [aws-amplify/amplify-cli#9413]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.5

### Amplify CLI Version

7.5.2

### What operating system are you using?

Mac Big Sur

### Amplify Categories

auth, storage, function, api, hosting

### Amplify Commands

push

### Describe the bug

Hi Amplify Team,

I've been running into an incredibly frustrating issue with Amplify for some time now and I haven't been able to find anyone else experiencing this in Discord or the GitHub issues on the CLI.

This issue didn't occur on my previous (intel based) MacBook but is pretty persistant on a 2020 M1 MBP running Big Sur. My suspicion is that it is caused by a rather large Amplify project (23 backend functions) with all of their node module dependencies.

Initially, after any reboot of my machine, upon trying an `amplify push`, I hit the following error:

```
An error occurred during the push operation: ENFILE: file table overflow, open '<SENSITIVE_PATH_REMOVED>/web-app/amplify/.temp/#current-cloud-backend/function/myapppuppeteerLayer/lib/nodejs/node_modules/tar-fs/test/fixtures/a/hello.txt'
```

I then increase the number of maximum open files using the following commands:

```
$ sudo sysctl -w kern.maxfiles=65536
$ sudo sysctl -w kern.maxfilesperproc=65536
$ ulimit -n 65536 
```

After which point, only about 10% of pushes succeed, the majority cause a corruption in the `amplify-meta.json` file and half-way through the push operation yield errors such as:

```
🛑 An error occurred during the push operation: Bad string at line 892,11166 >>>        "s3TemplateU ...
```

My only workaround is to take a backup of this file prior to each push and simply hope for the best. I then need to restore it before trying again.

Once again, only about 10% of pushes don't trigger this error and it's causing me to waste a lot of time, any help would be much appreciated.

### Expected behavior

Expect push to succeed without corrupting `amplify-meta.json`

### Reproduction steps

I cannot reproduce this issue in an empty directory since I believe it requires a large number of resources as part of the Amplify Project, however in my instance, it is simply reproduced by running `amplify push`.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by samputer** [comment]
This is possibly related to https://github.com/aws-amplify/amplify-cli/issues/8837 as I am experiencing similar symptoms

**Comment by cjihrig** [comment]
Thanks, we've received them. From looking at the files you sent, it looks like the corrupted version never finished writing to disk (it's a truncated version of the uncorrupted file). Since you mentioned that this works sometimes, my first guess is that the file is being written asynchronously somewhere in the code, but the calling code is not properly waiting for the write to finish, and we have a race condition.

**Comment by samputer** [comment]
Thanks @cjihrig. One thing to mention is that the files are sometimes full of null bytes from the top instead of from the bottom. I have also seen unrecognised characters in this file rather than simply nulls, but I don't have an example of those to hand.

It got to the state where almost no pushes were working, so I took the quite extreme step today of formatting this macbook.

The first push since doing this worked fine, however, as some pushes do work anyway (and it didn't always occur on this laptop), I'd be cautious in saying the problem is resolved.

I'll continue to test this over the next few days and see if it reoccurs.

**Comment by josefaidt** [comment]
Hey @samputer are you still experiencing this issue?

**Comment by samputer** [comment]
Hi @josefaidt - Thanks for reaching out. It looks like something specific to my development environment must have been borked as it has been working fine since I wiped the machine - I think we can close this issue and I'll re-open should it re-occur. Thanks for the help!

**Comment by josefaidt** [comment]
Hey @samputer I'm glad to hear that you haven't continuously experienced this and are back up and running! But yes if you see this occur again please reply back and we can re-open to investigate further 🙂
